name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tp1:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: make test
      working-directory: TP_Pointeurs
